package mensajes;


public enum M {
	CONEXION, CONFIRMAR_CONEX, PEDIR_FICHERO, PREPARADO_CS, PREPARADO_SC, CERRAR_CONEXION, CONFIRMAR_CIERRE, EMITIR_FICHERO, CONSULTAR_INFO, CONFIRMACION_CONSULTAR_INFO, ACTUALIZAR_INFO
}